name: ci

env:
  CONFIG_REPO_NAME: argocd-course-webapp-config
  
on:
  push:
    branches:
      - 'main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  promote-to-dev-environment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "promoting into dev environment!"

